### PR TITLE
[WIP] Adaptive ticks

### PR DESCRIPTION
**Pull request by asinghvi17**
In its current state, this PR uses PlotUtils and the Wilkinson tick-finding algorithm in order to compute "good" ticks.  It's a bit slow, though, so if you're OK with a dependency on MakieLayout, you could use the faster linear tick finder.

output

### CODE REVIEW

**Comment by mchitre** [comment]
I'm open to a MakieLayout dependency.

**Comment by mchitre** [comment]
@asinghvi17 I'm assuming this is not yet ready for review/merging, since you've marked it as WIP. Do ping me when you'd like me to take a deeper look.

**Comment by asinghvi17** [comment]
Will do.  We just merged MakieLayout into AbstractPlotting, so I'm waiting to see how that plays out before moving on this.

**Comment by mchitre** [comment]
@asinghvi17 any plans to move on this? Now that `MakieLayout` looks wonderful, it would make sense to replace the axes implementation to use it?

**Comment by mchitre** [comment]
No longer relevant with `v0.4`, as `InteractiveViz` now uses MakieLayout.

**Pull request closed without merging**
